language: ruby

sudo: true

script: bash make.sh
install: gem install asciidoctor --version=1.5.2 ; gem install asciidoctor-diagram --version=1.3.2 ; gem install pygments.rb --version=0.6.3

before_install:
  - sudo add-apt-repository ppa:dperry/ppa-graphviz-test -y
  - sudo apt-get update -q
  - sudo apt-get autoremove graphviz
  - sudo apt-get remove libcdt4
  - sudo apt-get remove libpathplan4
  - sudo apt-get install graphviz

notifications:
  email:
    - kill-bill-commits@googlegroups.com

rvm:
  - 2.2.0

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash update_gh-pages.sh'
