name: Publish

on:
  push:
    branches:
      - v3

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt update -qy
          sudo apt-get install -y graphviz curl
      - name: Set up RVM
        run: |
          curl -sSL https://get.rvm.io | bash
      - name: Set up Ruby
        run: |
          source $HOME/.rvm/scripts/rvm
          rvm install 2.2.0 --binary
          rvm --default use 2.2.0
      - name: Install Ruby dependencies
        run: |
          source $HOME/.rvm/scripts/rvm
          gem install asciidoctor --version=1.5.7.1
          gem install asciidoctor-diagram --version=1.5.9
          gem install pygments.rb --version=0.6.3
          gem install tilt --version=2.0.8
          gem install haml --version=5.0.4
          gem install thread_safe --version=0.3.6
          gem install slim --version 2.1.0
      - name: Build pages
        run: |
          source $HOME/.rvm/scripts/rvm
          bash make.sh
      - name: Publish pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          source $HOME/.rvm/scripts/rvm
          bash update_gh-pages.sh
